apiVersion: v1
kind: ReplicationController
metadata:
  name: coffee-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee
      annotations:     # If you plan on using a network other than the default you will need to uncomment these two lines
        diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
    spec:
      containers:
      - name: coffee
        image: nginxdemos/hello
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: ..data/nginx.conf
          name: coffee-config
      volumes:
      - configMap:
          name: coffee-config
        name: coffee-config
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  labels:
    app: coffee
spec:
  clusterIP: None    #Must be set to none to use the container network.
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: coffee