apiVersion: v1
kind: ReplicationController
metadata:
  name: tea-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tea
      annotations:     # If you plan on using a network other than the default you will need to uncomment these two lines
        diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
    spec:
      containers:
      - name: tea
        image: nginxdemos/hello
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: ..data/nginx.conf
          name: tea-config
      volumes:
      - configMap:
          name: tea-config
        name: tea-config
---
apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  labels:
    app: tea
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tea