title: "nginx demo"

myvalues


nginx-ingress:
  controller:
    name: nginx-ingress
    kind: deployment
    nginxplus: "false"
    hostNetwork: "false"
    image:
      repository: nginx/nginx-ingress
      tag: "1.1.1"
      pullPolicy: IfNotPresent

nginx:
  replicaCount: 2
  restartPolicy: Never
  image:
    repository: nginx
    tag: 1.11.0
    pullPolicy: IfNotPresent
  service:
    clusterIP: "None"

