kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: aquasec
  name: aqua-volume-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "high"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: aquasec
  name: aqua-db
  labels:
    app: aqua-db
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: aqua-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: aquasec
  name: aqua-db
spec:
  template:
    metadata:
      namespace: aquasec
      annotations:
          diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
      labels:
        app: aqua-db
      name: aqua-db
    spec:
      serviceAccount: aqua
      containers:
      - name: aqua-db
        image: aquasec/database:2.6
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aqua-db
                key: password
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-db
        ports:
        - containerPort: 5432
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: aqua-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: aquasec
  name: aqua-gateway
  labels:
    app: aqua-gateway
spec:
  clusterIP: None
  ports:
    - port: 3622
  selector:
    app: aqua-gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: aquasec
  name: aqua-gateway
spec:
  template:
    metadata:
      namespace: aquasec
      annotations:
          diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
      labels:
        app: aqua-gateway
      name: aqua-gateway
    spec:
      serviceAccount: aqua      
      containers:
      - name: aqua-gateway
        image: aquasec/gateway:2.6
        env:
          - name: SCALOCK_GATEWAY_PUBLIC_IP
            value: aqua-gateway
          - name: SCALOCK_DBUSER
            value: "postgres"
          - name: SCALOCK_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: aqua-db
                key: password
          - name: SCALOCK_DBNAME
            value: "scalock"
          - name: SCALOCK_DBHOST
            value: aqua-db
          - name: SCALOCK_DBPORT
            value: "5432"
          - name: SCALOCK_AUDIT_DBUSER
            value: "postgres"
          - name: SCALOCK_AUDIT_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: aqua-db
                key: password
          - name: SCALOCK_AUDIT_DBNAME
            value: "slk_audit"
          - name: SCALOCK_AUDIT_DBHOST
            value: aqua-db
          - name: SCALOCK_AUDIT_DBPORT
            value: "5432"
        ports:
        - containerPort: 3622
---
apiVersion: v1
kind: Service
metadata:
  namespace: aquasec
  name: aqua-web
  labels:
    app: aqua-web
spec:
  clusterIP: None
  ports:
    - port: 8080
  selector:
    app: aqua-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-web
  namespace: aquasec
spec:
  template:
    metadata:
      namespace: aquasec
      annotations:
          diamanti.com/endpoint0: '{"network":"blue","perfTier":"high"}'
      labels:
        app: aqua-web
      name: aqua-web
    spec:
      serviceAccount: aqua            
      containers:
      - name: aqua-web
        image: aquasec/server:2.6
        env:
          - name: SCALOCK_DBUSER
            value: "postgres"
          - name: SCALOCK_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: aqua-db
                key: password
          - name: SCALOCK_DBNAME
            value: "scalock"
          - name: SCALOCK_DBHOST
            value: aqua-db
          - name: SCALOCK_DBPORT
            value: "5432"
          - name: SCALOCK_AUDIT_DBUSER
            value: "postgres"
          - name: SCALOCK_AUDIT_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: aqua-db
                key: password
          - name: SCALOCK_AUDIT_DBNAME
            value: "slk_audit"
          - name: SCALOCK_AUDIT_DBHOST
            value: aqua-db
          - name: SCALOCK_AUDIT_DBPORT
            value: "5432"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-mount
        ports:
        - containerPort: 8080
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
---
