apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: registry-artifactory
  name: artifactory-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: artifactory-pro
        group: artifactory-demo
    spec:
      containers:
      - name: artifactory-pro
        image: docker.bintray.io/jfrog/artifactory-pro:5.8.3
        env:
        - name: DB_TYPE
          value: postgresql
        - name: DB_USER
          value: artifactory
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: postgresql-artifactory-service
        # Make sure to keep the memory java args aligned with the resources definitions
        - name: EXTRA_JAVA_OPTIONS
          value: "-Xms1g -Xmx2g"
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: "/var/opt/jfrog/artifactory"
          name: artifactory-pro-volume
        # Make sure to keep the resources set with values matching EXTRA_JAVA_OPTIONS above
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: '/artifactory/webapp/#/login'
            port: 8081
          initialDelaySeconds: 160
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/artifactory/webapp/#/login'
            port: 8081
          initialDelaySeconds: 280
          periodSeconds: 10
      volumes:
      - name: artifactory-pro-volume
        persistentVolumeClaim:
          claimName: artifactory-claim
      imagePullSecrets:
      - name: docker-reg-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: registry-artifactory
  name: artifactory
  labels:
    app: artifactory
    group: artifactory-demo
spec:
  clusterIP: None
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: artifactory-pro
