apiVersion: v1
kind: Service
metadata:
  namespace: registry-artifactory
  name: proxy
  labels:
    app: nginx-artifactory-service
    group: registry-artifactory
spec:
  clusterIP: None
  ports:
  - port: 80
    name: port-1
    protocol: TCP
    targetPort: 80
  - port: 443
    name: port-2
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-artifactory-deployment
