apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: registry-deployment
  name: registry-deployment
  namespace: registry-docker
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      name: registry
      labels:
        app: registry
      namespace: registry-docker
    spec:
      volumes:
      - name: registry-data
        flexVolume:
          driver: diamanti.com/volume
          fsType: xfs
          options:
            name: vol-registry-docker
            perfTier: high
            type: Simple
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-data
---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: registry-docker
spec:
  clusterIP: None
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000