apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
  namespace: docker-registry
spec:
  nodeSelector:
    kubernetes.io/hostname: appserv94
  volumes:
  - name: registry-data
    flexVolume:
      driver: diamanti.com/volume
      fsType: xfs
      options:
        name: vol-registry
        perfTier: high
        type: Simple
  - name: certificate
    hostPath:
      path: /home/diamanti/registry-tls
  containers:
  - name: registry
    image: registry:2
    imagePullPolicy: Always
    env:
      - name: REGISTRY_HTTP_ADDR
        value: "0.0.0.0:443"
      - name: REGISTRY_HTTP_TLS_CERTIFICATE
        value: "/certs/registry.crt"
      - name: REGISTRY_HTTP_TLS_KEY
        value: "/certs/registry.key"
    ports:
      - containerPort: 443
    volumeMounts:
      - mountPath: /var/lib/registry
        name: registry-data
      - mountPath: /certs/
        name: certificate
---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: docker-registry
spec:
  selector:
    app: registry
  ports:
    - port: 443
      targetPort: 443