apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
  namespace: docker-registry
spec:
  volumes:
  - name: registry-data
    flexVolume:
      driver: diamanti.com/volume
      fsType: xfs
      options:
        name: vol-registry
        perfTier: high
        type: Simple
  containers:
  - name: registry
    image: registry:2
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
    volumeMounts:
      - mountPath: /var/lib/registry
        name: registry-data
---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: docker-registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000