apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: registry-deployment
  name: registry-deployment
  namespace: registry-docker
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      name: registry
      labels:
        app: registry
      namespace: registry-docker
    spec:
      volumes:
      - name: registry-data
        flexVolume:
          driver: diamanti.com/volume
          fsType: xfs
          options:
            name: vol-registry-docker
            perfTier: high
            type: Simple
      - name: certificate
        configMap:
          name: docker-registry-tls
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: Always
        env:
          - name: REGISTRY_HTTP_ADDR
            value: "0.0.0.0:443"
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/certs/registry.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/certs/registry.key"
        ports:
          - containerPort: 443
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-data
          - mountPath: /certs/
            name: certificate
---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: registry-docker
spec:
  clusterIP: None
  selector:
    app: registry
  ports:
    - port: 443
      targetPort: 443