apiVersion: v1
kind: ReplicationController
metadata:
  name: tea-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tea
      annotations:
        diamanti.com/endpoint0: '{"network":"default","perfTier":"high"}'
    spec:
      containers:
      - name: tea
        image: nginxdemos/hello
        ports:
        - containerPort: 80
