apiVersion: v1
kind: Service
metadata:
  name: water-svc
  labels:
    app: water
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: water
