apiVersion: v1
kind: Pod
metadata:
  name: simple-app-<num>
  annotations: 
    diamanti.com/endpoint0: "{\"network\":\"blue\",\"perfTier\":\"high\"}"
  labels:
    app: simple-app
spec:
  hostNetwork: false
  containers:
  - image: docker.io/redis:latest
    name: simpl-app-<num>
    imagePullPolicy: Always
