apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-<num>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-<num>
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-vol-app  
  labels:
    app: simple-app
  annotations: 
    diamanti.com/endpoint0: "{\"network\":\"blue\",\"perfTier\":\"high\"}"
spec:
  containers:
  - image: docker.io/redis:latest
    imagePullPolicy: Always
    name: simple-vol-app
    resources:
    volumeMounts:
    - mountPath: /dATA
      name: vol-<num>
  volumes:
  - name: vol-<num>
    persistentVolumeClaim:
      claimName: pvc-<num>
