kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-<num>
  labels:
    type: local
spec:
  flexVolume:
    driver: diamanti.com/volume
    fsType: ext4
    options:
      name: pv-<num>
      perfTier: best-effort
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
