#!/bin/bash

. $(dirname ${BASH_SOURCE})/util.sh

run "dctl login -u admin"
run "clear"
run "dctl user role list"
#Create users"
run "echo \"----------------- Users in enterprise ------------------\""
run "dctl user group create user-admin-group --role-list user-edit"
run "dctl user create ua --local-auth --group-list user-admin-group -p Pass1234!"
run "dctl logout"
run "dctl login -u ua -p Pass1234!"
run "dctl user group create ug0 --role-list container-edit/ns0"
run "dctl user group create ug1 --role-list container-edit/ns1"
run "dctl user create u0 --local-auth --group-list ug0 -p Pass1234!"
run "dctl user create u1 --local-auth --group-list ug1 -p Pass1234!"
run "dctl user group create network-admin-group --role-list network-edit "
run "dctl user create na --local-auth --group-list network-admin-group -p Pass1234!"
run "dctl user group create storage-admin-group --role-list volume-edit"
run "dctl user create sa --local-auth --group-list storage-admin-group -p Pass1234!"
run "dctl user group create project-manager-group --role-list allcontainer-view,volume-view,network-view,node-view,perftier-view,user-view"
run "dctl user create pm --local-auth --group-list project-manager-group  -p Pass1234!"
run "dctl user group create cluster-manager-group --role-list allcontainer-edit,volume-edit,network-edit"
run "dctl user create cm --local-auth --group-list cluster-manager-group -p Pass1234!"
