---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "quay-storage-pvc"
      namespace: "quay-enterprise"
    spec:
      volumeName: "registry-quay-vol"
      storageClassName: ""
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
---
# Pleas note: PV will be ideally created in case of static volume creation, but in case if PV was delated because of crash or restart we need to recreate the PV for same static volume. So use it with kubectl apply to create if not present.
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "PersistentVolume"
    metadata:
      name: "registry-quay-vol"
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 110Gi
      flexVolume:
        driver: diamanti.com/volume
        fsType: xfs
        options:
          name: registry-quay-vol
          perfTier: high
