apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: dbaasselfservice-rc
  spec:
    replicas: 1
    selector:
      app: dbaasselfservice-app
    template:
      metadata:
        name: dbaasselfservice-app
        annotations: 
          diamanti.com/endpoint0: "{\"network\":\"default\",\"perfTier\":\"high\"}"
        labels:
          app: dbaasselfservice-app
      spec:
        hostNetwork: false
        containers:
        - image: guptaarvindk/dbaas-web:v3
          name: dbaasselfservice
          imagePullPolicy: Always
          command: [npm] 
          args: [start]
#          env:
#          - name: MHOST
#            value: "mongo-svc-0,mongo-svc-1,mongo-svc-2"
#          - name: MPORT
#            value: "27017"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: dbaasselfservice-app
    name: dbaasselfservice-app
  spec:
    clusterIP: None
    ports: 
    - nodePort: 0
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      name: dbaasselfservice-app
    sessionAffinity: None
    type: ClusterIP
