apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: nodejsmongo-rc
  spec:
    replicas: 1
    selector:
      app: nodejs-mongo-app
    template:
      metadata:
        name: nodejs-mongo-app
        annotations: 
          diamanti.com/endpoint0: "{\"network\":\"default\",\"perfTier\":\"high\"}"
        labels:
          app: nodejs-mongo-app
      spec:
        hostNetwork: false
        containers:
        - image: diamantisolutions/nodejs-mongo-app:v2
          name: nodejs-from-mongo
          imagePullPolicy: Always
          command: [npm] 
          args: [start]
          env:
          - name: MHOST
            value: "mongo-svc-0,mongo-svc-1,mongo-svc-2"
          - name: MPORT
            value: "27017"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: nodejs-mongo-app
    name: nodejs-mongo-app
  spec:
    clusterIP: None
    ports: 
    - nodePort: 0
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      name: nodejs-mongo-app
    sessionAffinity: None
    type: ClusterIP
