---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  storageClassName: high
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
