---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "PersistentVolume"
    metadata:
      name: "jenkins-vol"
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 100Gi
      flexVolume:
        driver: diamanti.com/volume
        fsType: xfs
        options:
          name: jenkins-vol
          perfTier: high
