---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: extensions/v1beta1
    kind: "Deployment"
    metadata:
      name: "jenkins-master"
      namespace: "jenkins"
      labels:
        name: "jenkins-master"
    spec:
      replicas: 1
      template:
        metadata:
          name: "jenkins-master"
          labels:
            name: "jenkins-master"
        spec:
          serviceAccountName: jenkins
          containers:
            - name: "jenkins"
              image: "guptaarvindk/jenkins:v1"
              imagePullPolicy: "Always"
              ports:
                - containerPort: 8080
                - containerPort: 50000
              resources:
                limits:
                  cpu: 4
                  memory: 4Gi
                requests:
                  cpu: 4
                  memory: 4Gi
              env:
                - name: MEM_REQUEST
                  valueFrom:
                    resourceFieldRef:
                      resource: requests.memory
                      divisor: "1Mi"
                - name: JENKINS_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: JENKINS_SERVICE_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                  # value: "jenkins"
                - name: JENKINS_SLAVE_AGENT_PORT
                  value: "50000"
                - name: JENKINS_PASS
                  value: "diamanti"
                - name: JENKINS_SERVICE_PORT
                  value: "8080"
                - name: JENKINS_OPTS
                  value: "--httpPort=$(JENKINS_SERVICE_PORT)"
                - name: JAVA_OPTS
                  value: "-Xmx$(MEM_REQUEST)m -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Djenkins.install.runSetupWizard=false"
              volumeMounts:
                - name: "jenkins"
                  mountPath: "/var/jenkins_home"
                - name: docker-sock-volume
                  mountPath: /var/run/docker.sock
          securityContext:
            fsGroup: 1000
          volumes:
            - name: docker-sock-volume
              hostPath:
                path: /var/run/docker.sock
            - name: "jenkins"
              persistentVolumeClaim:
                claimName: "jenkins"
---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "jenkins"
      namespace: "jenkins"
    spec:
      clusterIP: None
      type: ClusterIP
      selector:
        name: "jenkins-master"
      ports:
        -
          name: "http"
          port: 8080
          protocol: "TCP"
        -
          name: "slave"
          port: 50000
          protocol: "TCP"
