---
apiVersion: "v1"
kind: "List"
items:

  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "jenkins"
      namespace: "jenkins"
    spec:
      volumeName: "jenkins-vol"
      storageClassName: ""
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi

