apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    creationTimestamp: null
    labels:
      app: mssql
      diamanti.com/app: mssql-1
    name: mssql-1
  spec:
    replicas: 1
    selector:
      app: mssql
      diamanti.com/app: mssql-1
    template:
      metadata:
        annotations:
          diamanti.com/endpoint0: '{"network":"default","perfTier":"high"}'
        creationTimestamp: null
        labels:
          app: mssql
          diamanti.com/app: mssql-1
      spec:
        containers:
        - env:
          - name: SA_PASSWORD
            value: "P455word1"
          - name: ACCEPT_EULA
            value: "Y"
          image: microsoft/mssql-server-linux
          imagePullPolicy: IfNotPresent
          name: mssql
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
              cpu: 8000m
              memory: 8Gi 
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/opt/mssql
            name: mssql-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          -
            name: "mssql-data"
            flexVolume:
              driver: "diamanti.com/volume"
              fsType: "xfs"
              options:
                name: "mssql-1"
                perfTier: "high"
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mssql-1
  spec:
    clusterIP: None
    ports:
    - name: tcp
      port: 1433
      protocol: TCP
      targetPort: 1433
    selector:
      diamanti.com/app: mssql-1
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
