apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress-1
  name: haproxy-ingress-1
spec:
  selector:
    matchLabels:
      run: haproxy-ingress-1
  template:
    metadata:
      labels:
        run: haproxy-ingress-1
        app: haproxy-ingress-1
      annotations:     
        diamanti.com/endpoint0: '{"endpointId":"haproxy-ep-1","perfTier":"high"}'
    spec:
      nodeSelector:
        app: lb
      hostname: haproxy-1
      containers:
      - name: haproxy-ingress
        image: guptaarvindk/haproxy-ingress:peers
        imagePullPolicy: Always
        args:
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend  # here is where the default backend (the 404) is set
        #- --default-ssl-certificate=$(POD_NAMESPACE)/haproxy-tls   # here is where the secret is used
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress # here is the configmap with  the haproxy configuration options
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-1
  labels:
    app: haproxy-ingress-1
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: haproxy-ingress-1