{{- if eq .Values.controller.kind "deployment" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.controller.name }}
spec:
  replicas: {{ .Values.controller.replicacount | default 1 }}
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
{{- if .Values.controller.serviceAccountName }}
      serviceAccountName: {{ .Values.controller.serviceAccountName }}
{{- end }}
      hostNetwork: {{ .Values.controller.hostNetwork }}
      containers:
      - image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        name: {{ .Values.controller.name }}
        imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
{{- if eq .Values.controller.nginxplus "true" }}
          - -nginx-plus
{{- end }}
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
{{- end }}