apiVersion: batch/v1
kind: Job
metadata:
  name: consul-join
spec:
  template:
    metadata:
      name: consul-join
    spec:
      containers:
        - name: consul
          image: consul:0.8.1
          command:
            - "/bin/consul"
            - "join"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "-http-addr=pg-1:8500"
            - "pg-0"
            - "pg-2"
      restartPolicy: Never
