apiVersion: v1
kind: ReplicationController
metadata:
  namespace: nginx-lb
  name: coffee-rc-<lb_num>
  labels:
    app: coffee
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee
        instance: coffee-<lb_num>
      annotations:
        diamanti.com/endpoint0: '{"network":"red","perfTier":"best-effort"}'
    spec:
      nodeSelector:
        kubernetes.io/hostname: appserv94
      containers:
      - name: coffee
#        image: nginxdemos/hello
#        image: nginx
        image: guptaarvindk/nginx-web:perf
#        resources:
#          requests:
#            #memory: "64Mi"
#            cpu: "1"
#          limits:
#            #memory: "128Mi"
#            cpu: "1"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: "..data/nginx.conf"
          name: nginx-config
      volumes:
      - configMap:
          name: nginx-config
        name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx-lb
  name: coffee-svc-<lb_num>
  labels:
    app: coffee
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: coffee
    instance: coffee-<lb_num>
