apiVersion: v1
kind: ReplicationController
metadata:
  name: coffee-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee
      annotations:
        diamanti.com/endpoint0: '{"network":"default","perfTier":"high"}'
    spec:
      containers:
      - name: coffee
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: coffee-config
      volumes:
      - configMap:
          name: coffee-config
        name: coffee-config
