# Default values for nginx.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1


image:
  repository: guptaarvindk/nginx-web:perf
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
