apiVersion: batch/v1
kind: Job
metadata:
  name: consul-join
spec:
  template:
    metadata:
      name: consul-join
      annotations:
        diamanti.com/endpoint0: '{"network":"default","perfTier":"high"}'
    spec:
      containers:
        - name: consul
          image: consul:0.8.1
          command:
            - "/bin/consul"
            - "join"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "-http-addr=172.16.167.4:8500"
            - "172.16.167.5"
            - "172.16.167.6"
      restartPolicy: Never
